name: Public Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create filtered archive
      run: |
        git archive --format=tar.gz --prefix=heaven-framework/ HEAD | \
        tar --delete --wildcards 'heaven-framework/ideas/*' | \
        gzip > heaven-framework-v${{ inputs.version }}.tar.gz
    
    - name: Create public release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create v${{ inputs.version }} \
          --title "HEAVEN Framework v${{ inputs.version }}" \
          --notes "Public release of HEAVEN Framework" \
          --draft \
          heaven-framework-v${{ inputs.version }}.tar.gz
